### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'eachItemGraphicEl' of undefined

### ISSUE THREAD

**Issue by Carrotzpc** [hustcc/echarts-for-react#33]
如题，最近几天出现的错误，详细信息如下：
```js
Uncaught (in promise) TypeError: Cannot read property 'eachItemGraphicEl' of undefined
    at ExtendedClass._renderPointer (http://localhost/webpack_dll/lib.js:178362:25)
    at ExtendedClass._renderMain (http://localhost/webpack_dll/lib.js:178219:19)
    at ExtendedClass.render (http://localhost/webpack_dll/lib.js:178138:19)
    at ECharts.<anonymous> (http://localhost/webpack_dll/lib.js:137917:24)
    at ExtendedClass.<anonymous> (http://localhost/webpack_dll/lib.js:139205:21)
    at Array.forEach (native)
    at each (http://localhost/webpack_dll/lib.js:139678:18)
    at ExtendedClass.eachSeries (http://localhost/webpack_dll/lib.js:139203:14)
    at ECharts.doRender (http://localhost/webpack_dll/lib.js:137914:18)
    at ECharts.update (http://localhost/webpack_dll/lib.js:137351:23)
_renderPointer	@	GaugeView.js:275
_renderMain	@	GaugeView.js:132
render	@	GaugeView.js:51
(anonymous)	@	echarts.js:1230
(anonymous)	@	Global.js:499
each	@	util.js:260
eachSeries	@	Global.js:497
doRender	@	echarts.js:1227
update	@	echarts.js:664
prepareAndUpdate	@	echarts.js:793
echartsProto.setOption	@	echarts.js:290
renderEchartDom	@	echarts-for-react.js:81
ReactEcharts_componentDidMount	@	echarts-for-react.js:33
(anonymous)	@	ReactCompositeComponent.js:264
measureLifeCyclePerf	@	ReactCompositeComponent.js:74
(anonymous)	@	ReactCompositeComponent.js:263
notifyAll	@	CallbackQueue.js:67
close	@	ReactReconcileTransaction.js:81
closeAll	@	Transaction.js:204
perform	@	Transaction.js:151
perform	@	Transaction.js:138
perform	@	ReactUpdates.js:90
flushBatchedUpdates	@	ReactUpdates.js:173
closeAll	@	Transaction.js:204
perform	@	Transaction.js:151
batchedUpdates	@	ReactDefaultBatchingStrategy.js:63
enqueueUpdate	@	ReactUpdates.js:201
enqueueUpdate	@	ReactUpdateQueue.js:25
enqueueSetState	@	ReactUpdateQueue.js:210
ReactComponent.setState	@	ReactComponent.js:64
handleChange	@	connect.js:302
dispatch	@	createStore.js:186
dispatch	@	instrument.js:599
(anonymous)	@	index.js:208
fetchApi.then.actionWith.type	@	api.js:199
```
经过调试发现应该是 `echarts` 最近的版本(`@3.4.0 `)更新导致的，建议 `package.json` 修改下版本控制：
```
"echarts": "^3.1.1" => "echarts": "~3.1.1"
```

**Comment by hustcc** [comment]
建议到 echarts 上提交 issue，echarts-for-echarts 是一个组件，应该不太好过多的限制用户选择那个版本。

**Comment by Carrotzpc** [comment]
嗯，我自己在 `package.json` 里面限制了 `echarts` 的版本

**Comment by hustcc** [comment]
^_^ :+1:
